#  _____     ___ ____
#   ____|   |    ____|      PS2 OpenSource Project
#  |     ___|   |____       (C)2020, Francisco Javier Trujillo Mata 
#						      ( fjtrujy@gmail.com )
#  ---------------------------------------------------------------------------


all: demos

clean:
	$(MAKE) -C demo1 clean
	$(MAKE) -C demo2 clean
	$(MAKE) -C demo3 clean
	$(MAKE) -C demo4 clean
	$(MAKE) -C demo5 clean

demos:
	$(MAKE) -C demo1
	$(MAKE) -C demo2
	$(MAKE) -C demo3
	$(MAKE) -C demo4
	$(MAKE) -C demo5